parameters:
    modera_security.session_handler.db_username: ~
    modera_security.session_handler.db_password: ~
    modera_security.session_handler.dns_or_url: '%env(DATABASE_URL)%'
    modera_security.session_handler.options:
        db_table: modera_security_session
        db_id_col: sess_id
        db_data_col: sess_data
        db_time_col: sess_time
        db_lifetime_col: sess_lifetime
        db_username: '%modera_security.session_handler.db_username%'
        db_password: '%modera_security.session_handler.db_password%'

services:
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%modera_security.session_handler.dns_or_url%'
            - "%modera_security.session_handler.options%"
