imports:
    - { resource: '@ModeraSecurityBundle/Resources/config/config.yml' }
    - { resource: '@ModeraSecurityBundle/Resources/config/firewalls.yml' }

security:
    access_control: '%modera_security.config.access_control%'
